# Generated by Django 5.0.4 on 2026-06-08 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasinoGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('provider', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('slots', 'Slots'), ('table-games', 'Table Games'), ('live-casino', 'Live Casino'), ('jackpots', 'Jackpots'), ('game-shows', 'Game Shows')], default='slots', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='casino/games/')),
                ('image_url', models.URLField(blank=True)),
                ('is_new', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('rtp', models.DecimalField(blank=True, decimal_places=2, help_text='Return to player %', max_digits=5, null=True)),
                ('min_bet', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('max_bet', models.DecimalField(decimal_places=2, default=100000, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'casino_games',
                'ordering': ['-is_popular', '-is_new', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CasinoGameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('finished', 'Finished')], default='active', max_length=10)),
                ('amount_wagered', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount_won', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('RWF', 'RWF')], default='RWF', max_length=3)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='casino.casinogame')),
            ],
            options={
                'db_table': 'casino_sessions',
                'ordering': ['-started_at'],
            },
        ),
    ]
